### ISSUE TITLE
com port selection

### ISSUE THREAD

**Issue by pbanj** [pine64/pinecil-firmware-updater#11]
i have other devices that use com ports and i have to unplug them every time i want to update. it would be nice to have the option to select what com port to use. otherwise it just fails unless you unplug the other stuff.

**Comment by gamelaster** [comment]
@pbanj it should work fine, unless the USB device you use have same VID and PID as Pinecil

**Comment by pbanj** [comment]
let me check the worst offender

**Comment by pbanj** [comment]
the vid and pid are different between them. also neither are connected through a hub.

![image](https://user-images.githubusercontent.com/17306233/120708451-95ef8c80-c489-11eb-91de-6ab53833cfb1.png)

**Comment by gamelaster** [comment]
Then it should work absolutely good. Can you more describe how this happens?

**Comment by pbanj** [comment]
well i guess it can be closed. just went to grab a screenshot of what it says and it decided it would flash fine. ive been having this issue since the first time i updated lol.
