### ISSUE TITLE
can't flash custom firmware

### ISSUE THREAD

**Issue by pbanj** [pine64/pinecil-firmware-updater#3]
just throws this error
![image](https://user-images.githubusercontent.com/17306233/105093530-e2a17080-5a70-11eb-8796-8983e028945c.png)

should note, selecting a firmware from the dropdown list works fine

**Comment by gamelaster** [comment]
Hello @pbanj ,

Thanks for reporting. I know about this issue and it will be fixed in v1.1.

- gamiee
