### ISSUE TITLE
MASS_ERASE get_status fail on Flash

### ISSUE THREAD

**Issue by RyanHutchison** [pine64/pinecil-firmware-updater#5]
I am unable to flash my new Pinecil.

Invalid DFU suffix signature A valid DFU suffix will be required in a future dfu-util release!!! Error during special command "MASS_ERASE" get_status 

![Screenshot 2021-01-27 104624](https://user-images.githubusercontent.com/7422225/106024014-f3fc0580-608c-11eb-9541-48bc4bf3799f.png)

I also attempted to load to with the GD MCU 32 tool, but it was not listing any device available. 

![Screenshot 2021-01-27 104854](https://user-images.githubusercontent.com/7422225/106025385-4f7ac300-608e-11eb-80ac-899a0f2a3746.png)

Windows 10 Pro using the loaded WinUSB adapter.

**Comment by gamelaster** [comment]
GD32 MCU Tool need another driver, not WinUSB.

About the problem, can you please in directory with pinecil updater execute `dfu-util.exe -l` and send response here?

Thanks

**Comment by RyanHutchison** [comment]
Cannot open DFU device 0a5c:21e8
Found DFU: [28e9:0189] ver=0100, devnum=100, cfg=1, intf=0, path="2-3", alt=1, name="@Option Bytes  /0x1FFFF800/01*016Be", serial="??"
Found DFU: [28e9:0189] ver=0100, devnum=100, cfg=1, intf=0, path="2-3", alt=0, name="@Internal Flash  /0x08000000/128*001Kg", serial="??"

**Comment by RyanHutchison** [comment]
I also loaded the GD MCU 32 drivers and it flashed fine with that tool.

**Comment by gamelaster** [comment]
Then it's not Flash Size error problem. Well, I found one person having same problem, but he probably didn't found solution.
Can be issue with `dfu-util`, since it works for you with GD MCU Tool. Will take look. Thanks for reporting.

**Comment by RyanHutchison** [comment]
Here is the screenshot from the MCU tool if it helps:

![Screenshot 2021-01-27 125129](https://user-images.githubusercontent.com/7422225/106039208-76d98c00-609e-11eb-86cb-55a7204be563.png)

**Comment by unwiredben** [comment]
I'm having the same problem with the Pinecil I received today from the January batch.  My output from dfu-util.exe -i is

`C:\Users\bcombee\Downloads\pinecil_firmware_updater_win64_1.2>dfu-util.exe -l
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Cannot open DFU device 17e9:6006
Cannot open DFU device 17e9:6006
Found DFU: [28e9:0189] ver=0100, devnum=56, cfg=1, intf=0, path="1-2", alt=1, name="@Option Bytes  /0x1FFFF800/01*016Be", serial="??"
Found DFU: [28e9:0189] ver=0100, devnum=56, cfg=1, intf=0, path="1-2", alt=0, name="@Internal Flash  /0x08000000/128*001Kg", serial="??"`

**Comment by DooMMasteR** [comment]
Also not working for me.

**Comment by codefaux** [comment]
![image](https://user-images.githubusercontent.com/42219549/107213428-3f7faf00-69bd-11eb-9081-892e75d1b3cf.png)


`dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Found DFU: [28e9:0189] ver=0100, devnum=62, cfg=1, intf=0, path="3-14", alt=1, name="@Option Bytes  /0x1FFFF800/01*016Be", serial="??"
Found DFU: [28e9:0189] ver=0100, devnum=62, cfg=1, intf=0, path="3-14", alt=0, name="@Internal Flash  /0x08000000/128*001Kg", serial="??"`

Success with "GD32 MCU DFU Tool" version 3.8.2.9056 using "GD DFU Drivers" version 3.6.6.6167 -- GD32 DFU Tool set to Verify and Erase All
(http://www.gd32mcu.com/en/download/7?kw=)

Unit indicated settings reset on reboot as expected. Device functions as expected.

Manually installing driver provided with Pinecil Firmware Updater v1.2 and attempting to flash over successfully flashed IronOS 2.14.1 from GD32 MCU DFU Tool -- same result.

**Comment by gamelaster** [comment]
@codefaux so even GD32 tool doesn't work for you?

**Comment by gamelaster** [comment]
It should be fixed in 1.3. Please let me know if it still persists.

**Comment by codefaux** [comment]
@gamelaster GD32 Tool worked; just indicating that using GD32 Tool did not 'repair' the inability to use the Pinecil Updater - it's just a workaround. (Mostly for clarification/documentation.)

**Comment by gamelaster** [comment]
@codefaux yes, I know, that's why I made some changes and it should work in 1.3 without issues

**Comment by RyanHutchison** [comment]
Tested and seemd to be functioning now.

**Comment by gamelaster** [comment]
@RyanHutchison Great, thank you very much for letting me know.
