### ISSUE TITLE
v1.2 incorrectly reports a new version is available

### ISSUE THREAD

**Issue by athisun** [pine64/pinecil-firmware-updater#7]
v1.2 incorrectly reports that a new version is available because the info.json hosted at http://pinecil.pine64.org/updater/info.json is outdated, reporting v1.1 as the latest version.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/7977719/106298759-0732ef00-62a0-11eb-8bd7-0a4b5c60dfdd.png">

Ideally this line would be updated to convert the version string into a float, then make a greater-than comparison to the current version, instead of an inequality check.

https://github.com/pine64/pinecil-firmware-updater/blob/b3762d06609a9384ee9179dd63c786c988382109/mainwindow.cpp#L123

https://doc.qt.io/qt-5/qjsonvalue.html#toDouble
```cpp
if (json["latest_version"].ToDouble() > 1.2) { 
```

Note that this method only works for major-minor versioning. Semantic versioning would require splitting the string by '.' and comparing each version component.

**Comment by gamelaster** [comment]
Thank you for reporting, I forget to change version on server.

And this idea with double conversion is very good, I will add it in next version.
Thanks :)
