### ISSUE TITLE
v1.3 Windows package, reports newer version available

### ISSUE THREAD

**Issue by krzysztofzawadzki** [pine64/pinecil-firmware-updater#9]
Release: v1.3
OS: Windows 10
App: Pinecil Firmware Updater
Used download link: https://github.com/pine64/pinecil-firmware-updater/releases/download/1.3/pinecil_firmware_updater_win64_1.3.zip

App reports that there is newer version available than already fetched v1.3
![obraz](https://user-images.githubusercontent.com/47650317/108137207-bc94dd80-70bb-11eb-8c6a-fc4f13201965.png)

App About Window shows v1.2
![obraz](https://user-images.githubusercontent.com/47650317/108137162-a555f000-70bb-11eb-93c6-677f184cdb0c.png)

**Comment by gamelaster** [comment]
Hi, thanks for reporting. I somehow uploaded v1.3 version with v1.2 tag. I re-uploaded  it in releases.
Thanks for letting me know.
